PAUSE_SIZE = '200x150'

START_FULLSCREEN = True

BG_DEFAULT_COLOUR = "gray94"

STARTING_TILE = "D"

PLAYER_COLOUR_LIST = ["Red", "Blue", "Lime", "Yellow", "Magenta", "Cyan"]

CASTLE_COLOUR = "Orange"
ROAD_COLOUR = "Grey"
FIELD_COLOUR = "Green"
MONESTRY_COLOUR = "indianred1"
COA_COLOUR_1 = "White"
COA_COLOUR_2 = "Blue"
UNCLAIMED_BG_COLOUR = "White"

TILE_SIZE = 100
TILE_GRID_X = 11
TILE_GRID_Y = 9