PAUSE_SIZE = '200x150'

START_FULLSCREEN = True

BG_DEFAULT_COLOUR = "gray94"

STARTING_TILE = "D"

CASTLE_COLOUR = "Orange"
ROAD_COLOUR = "Grey"
FIELD_COLOUR = "Green"
MONESTRY_COLOUR = "Red"
COA_COLOUR_1 = "White"
COA_COLOUR_2 = "Blue"

TILE_SIZE = 100